#
# Module manifest for module 'CoreGame'
#
# Generated by: PowerShell Leafmap Game Team
#
# Generated on: 21/07/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'CoreGame.psm1'

# Version number of this module.
ModuleVersion = '0.2.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '789845cf-5fbb-4bc5-8712-79776322652a'

# Author of this module
Author = 'PowerShell Leafmap Game Team'

# Company or vendor of this module
CompanyName = 'PowerShellYoungTeam'

# Copyright statement for this module
Copyright = '(c) 2025 PowerShell Leafmap Game Team. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell Leafmap RPG Game - CoreGame module providing logging, events, state management, pathfinding, communication, and command registry systems.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NOTE: We import submodules from CoreGame.psm1 using Import-Module to properly handle scoping
# NestedModules = @()

# Functions to export from this module
# Using '*' because submodules are imported via Import-Module in root module
# The explicit list is documented here for reference:
# - CoreGame: Initialize-GameEngine
# - GameLogging: Initialize-GameLogging, Write-GameLog, Set-LoggingConfig, Get-LoggingInfo,
#                Enable-DebugLogging, Disable-DebugLogging, Write-DebugLog, Write-ErrorLog
# - DataModels: New-GameEntity, New-PlayerEntity, New-NPCEntity, New-ItemEntity,
#               New-LocationEntity, New-QuestEntity, New-FactionEntity
# - EventSystem: Initialize-EventSystem, Register-GameEvent, Send-GameEvent, Get-GameEvent,
#                Invoke-EventHandlers, Process-JavaScriptCommands, Start-EventProcessing, etc.
# - StateManager: Initialize-StateManager, Register-GameEntity, Update-GameEntityState,
#                 Get-GameEntity, Save-GameState, Load-GameState, etc.
# - PathfindingSystem: Initialize-PathfindingSystem, Start-UnitMovement, Update-UnitPosition, etc.
# - CommunicationBridge: Initialize-CommunicationBridge, Send-BridgeCommand, Receive-BridgeCommands, etc.
# - CommandRegistry: Initialize-CommandRegistry, Register-GameCommand, Invoke-GameCommand, etc.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

